buttons_size: 20
additional_html: ''
additional_css: ''
additional_js: ''
universal_button: default
custom_universal_button: 'https://image.flaticon.com/icons/svg/61/61472.svg'
universal_button_placement: before
no_3p: false
_core:
  default_config_hash: 8aJF-FDdnrk-N2gLGWFQcLZIpuJZA0BE9NtgXTVJfVk
