module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_translation: 0
  config_update: 0
  contact: 0
  contact_block: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  language: 0
  layout_plugin: 0
  libraries: 0
  link: 0
  linkit: 0
  locale: 0
  menu_block: 0
  menu_ui: 0
  mmenu: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panelizer_quickedit: 0
  panels: 0
  panels_everywhere: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  responsive_menu: 0
  rest: 0
  restui: 0
  search: 0
  serialization: 0
  shortcut: 0
  styleguide: 0
  superfish: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  racc_theme: 0
  patternlab: 0
  racc_pattern_lab: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
